spring:
  datasource:
    url: jdbc:h2:mem:coderhouse
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: coderhouse
      password: 123
jwt:
  expiration: 60000
  secret: springbootjwtcoderhouse